name: tvOS Build Size Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        
    - name: Build tvOS app for simulator
      run: |
        cd ios
        xcodebuild -workspace TVTest.xcworkspace -scheme TVTest -configuration Release -destination 'platform=tvOS Simulator,name=Apple TV' build
        
    - name: Get app size
      run: |
        cd ios
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "TVTest.app" -type d)
        echo "App path: $APP_PATH"
        
        # 获取应用总大小
        APP_SIZE=$(du -sh "$APP_PATH" | cut -f1)
        echo "Total app size: $APP_SIZE"
        
        # 获取详细的大小信息
        echo "Detailed size information:"
        du -sh "$APP_PATH"/*
        
        # 使用新的环境文件语法设置输出
        echo "APP_SIZE=$APP_SIZE" >> $GITHUB_ENV
        echo "APP_SIZE=$APP_SIZE" >> $GITHUB_OUTPUT

    - name: Test tvOS render time
      run: |
        cd ios
        # 启动模拟器
        xcrun simctl boot "Apple TV"
        
        # 安装应用
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "TVTest.app" -type d)
        xcrun simctl install booted "$APP_PATH"
        
        # 启动应用并收集日志
        echo "Starting performance test..."
        
        # 启动应用
        xcrun simctl launch booted com.TVTest &
        APP_PID=$!
        
        # 等待应用启动
        sleep 5
        
        # 收集日志
        echo "Collecting performance logs..."
        xcrun simctl spawn booted log show --predicate 'process == "TVTest"' --last 5m > app.log
        
        # 分析日志中的时间戳
        echo "Analyzing performance data..."
        START_TIME=$(grep "viewDidLoad" app.log | head -n 1 | awk '{print $1}')
        END_TIME=$(grep "viewDidAppear" app.log | head -n 1 | awk '{print $1}')
        
        if [ ! -z "$START_TIME" ] && [ ! -z "$END_TIME" ]; then
          # 转换时间戳为秒数
          START_SECONDS=$(date -j -f "%Y-%m-%d %H:%M:%S.%3N" "$START_TIME" +%s.%3N)
          END_SECONDS=$(date -j -f "%Y-%m-%d %H:%M:%S.%3N" "$END_TIME" +%s.%3N)
          
          # 计算时间差
          RENDER_TIME=$(echo "$END_SECONDS - $START_SECONDS" | bc)
          echo "ViewDidLoad to ViewDidAppear time: $RENDER_TIME seconds"
          echo "RENDER_TIME=$RENDER_TIME" >> $GITHUB_ENV
          echo "RENDER_TIME=$RENDER_TIME" >> $GITHUB_OUTPUT
        else
          echo "Could not find viewDidLoad or viewDidAppear timestamps in logs"
          echo "Log contents:"
          cat app.log
        fi
        
        # 关闭应用和模拟器
        kill $APP_PID 2>/dev/null || true
        xcrun simctl shutdown "Apple TV" 