name: tvOS Build Size Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        
    - name: Build tvOS app for simulator
      run: |
        cd ios
        xcodebuild -workspace TVTest.xcworkspace -scheme TVTest -configuration Release -destination 'platform=tvOS Simulator,name=Apple TV' build
        
    - name: Get app size
      run: |
        cd ios
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "TVTest.app" -type d)
        echo "App path: $APP_PATH"
        du -sh "$APP_PATH"
        echo "APP_SIZE=$(du -sh "$APP_PATH" | cut -f1)" >> $GITHUB_ENV
        
    - name: Upload build info
      uses: actions/upload-artifact@v3
      with:
        name: build-info
        path: |
          ios/build/Build/Products/Release-appletvsimulator/TVTest.app
          ios/build/Build/Products/Release-appletvsimulator/TVTest.app.dSYM 