name: tvOS Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        
    - name: Install tvOS Simulator
      run: |
        xcversion simulators --install="Apple TV 4K (3rd generation) (EDA18377-A6DD-42CF-A5FA-A4620737EAC6)"
        
    - name: Build and Test tvOS app
      run: |
        cd ios
        pod install
        xcodebuild -workspace TVTest.xcworkspace -scheme TVTest-tvOS -configuration Debug -sdk appletvsimulator -destination 'platform=tvOS Simulator,id=EDA18377-A6DD-42CF-A5FA-A4620737EAC6' build test
        
    - name: Get app size
      run: |
        cd ios
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "TVTest.app" -type d)
        echo "App path: $APP_PATH"
        
        # 获取应用总大小
        APP_SIZE=$(du -sh "$APP_PATH" | cut -f1)
        echo "Total app size: $APP_SIZE"
        
        # 获取详细的大小信息
        echo "Detailed size information:"
        du -sh "$APP_PATH"/*
        
        # 设置输出变量
        echo "APP_SIZE=$APP_SIZE" >> $GITHUB_ENV
        echo "APP_SIZE=$APP_SIZE" >> $GITHUB_OUTPUT 